#!/bin/bash

#USAGE:
#with no argument: kill the running instance if any and start new;
#argument 'stop': kill the running instance if any and exit;

if [[ ":$PATH:" == *"/home/ubuntu/amazon-kinesis-video-streams-producer-sdk-cpp-1.4.3/kinesis-video-native-build/downloads/local/bin:"* ]]; 
then
    echo "PATH is correct"
else
    export PATH=/home/ubuntu/amazon-kinesis-video-streams-producer-sdk-cpp-1.4.3/kinesis-video-native-build/downloads/local/bin:$PATH
fi

if [[ ":$LD_LIBRARY_PATH:" == *"/home/ubuntu/amazon-kinesis-video-streams-producer-sdk-cpp-1.4.3/kinesis-video-native-build/downloads/local/lib:"* ]]; 
then
    echo "LD_LIBRARY_PATH is correct"
else
    export LD_LIBRARY_PATH=/home/ubuntu/amazon-kinesis-video-streams-producer-sdk-cpp-1.4.3/kinesis-video-native-build/downloads/local/lib:$LD_LIBRARY_PATH
fi

if [[ ":$GST_PLUGIN_PATH:" == *"/usr/lib/aarch64-linux-gnu/tegra/:/home/ubuntu/amazon-kinesis-video-streams-producer-sdk-cpp-1.4.3/kinesis-video-native-build/downloads/local/lib/:/usr/lib/aarch64-linux-gnu/:"* ]]; 
then
    echo "GST_PLUGIN_PATH is correct"
else
    export GST_PLUGIN_PATH=/usr/lib/aarch64-linux-gnu/tegra/:/home/ubuntu/amazon-kinesis-video-streams-producer-sdk-cpp-1.4.3/kinesis-video-native-build/downloads/local/lib/:/usr/lib/aarch64-linux-gnu/:$GST_PLUGIN_PATH
fi

echo CLEARING
ps aux | grep '[!] kvssink' | awk '{print $2}' | xargs sudo kill -9

if [ "$1" == 'stop' ]; then
    echo "STOPPED"
    exit
fi

echo STARTING
nohup gst-launch-1.0 nvcamerasrc ! 'video/x-raw(memory:NVMM), width=(int)1920, height=(int)1080, format=(string)I420, framerate=(fraction)24/1' ! omxh264enc qp-range='1,-1:-1,-1:-1,-1', iframeinterval=24 ! kvssink access-key= secret-key= stream-name=test11 storage-size=512 max-latency=30 fragment-duration=10 key-frame-fragmentation=true fragment-acks=true framerate=24 log-config='./kvs_log_configuration'  &

sleep 3
RESULT=`ps aux | grep '[!] kvssink'`
if [ "${RESULT:-null}" = null ]; then
    echo "ERROR!"
else
    echo "OK"
fi

