#!/bin/bash

if [[ ":$PATH:" == *"/home/ubuntu/amazon-kinesis-video-streams-producer-sdk-cpp-1.4.3/kinesis-video-native-build/downloads/local/bin:"* ]]; 
then
    echo "PATH is correct"
else
    export PATH=/home/ubuntu/amazon-kinesis-video-streams-producer-sdk-cpp-1.4.3/kinesis-video-native-build/downloads/local/bin:$PATH
fi

if [[ ":$LD_LIBRARY_PATH:" == *"/home/ubuntu/amazon-kinesis-video-streams-producer-sdk-cpp-1.4.3/kinesis-video-native-build/downloads/local/lib:"* ]]; 
then
    echo "LD_LIBRARY_PATH is correct"
else
    export LD_LIBRARY_PATH=/home/ubuntu/amazon-kinesis-video-streams-producer-sdk-cpp-1.4.3/kinesis-video-native-build/downloads/local/lib:$LD_LIBRARY_PATH
fi

if [[ ":$GST_PLUGIN_PATH:" == *"/usr/lib/aarch64-linux-gnu/tegra/:/home/ubuntu/amazon-kinesis-video-streams-producer-sdk-cpp-1.4.3/kinesis-video-native-build/downloads/local/lib/:/usr/lib/aarch64-linux-gnu/:"* ]]; 
then
    echo "GST_PLUGIN_PATH is correct"
else
    export GST_PLUGIN_PATH=/usr/lib/aarch64-linux-gnu/tegra/:/home/ubuntu/amazon-kinesis-video-streams-producer-sdk-cpp-1.4.3/kinesis-video-native-build/downloads/local/lib/:/usr/lib/aarch64-linux-gnu/:$GST_PLUGIN_PATH
fi

nohup gst-launch-1.0 nvcamerasrc ! 'video/x-raw(memory:NVMM), width=(int)1920, height=(int)1080, format=(string)I420, framerate=(fraction)24/1' ! omxh264enc ! kvssink access-key= secret-key= stream-name=test11 storage-size=512 &

echo "**********************************************************"
echo OK
echo "**********************************************************"

